<?php

namespace App\Constants;

use App\Enums\Settings\SettingKey;

enum GlobalConfig
{
	const COUNTRIES = [
		['name' => 'Afghanistan', 'code' => 'AF'],
		['name' => 'Åland Islands', 'code' => 'AX'],
		['name' => 'Albania', 'code' => 'AL'],
		['name' => 'Algeria', 'code' => 'DZ'],
		['name' => 'American Samoa', 'code' => 'AS'],
		['name' => 'AndorrA', 'code' => 'AD'],
		['name' => 'Angola', 'code' => 'AO'],
		['name' => 'Anguilla', 'code' => 'AI'],
		['name' => 'Antarctica', 'code' => 'AQ'],
		['name' => 'Antigua and Barbuda', 'code' => 'AG'],
		['name' => 'Argentina', 'code' => 'AR'],
		['name' => 'Armenia', 'code' => 'AM'],
		['name' => 'Aruba', 'code' => 'AW'],
		['name' => 'Australia', 'code' => 'AU'],
		['name' => 'Austria', 'code' => 'AT'],
		['name' => 'Azerbaijan', 'code' => 'AZ'],
		['name' => 'Bahamas', 'code' => 'BS'],
		['name' => 'Bahrain', 'code' => 'BH'],
		['name' => 'Bangladesh', 'code' => 'BD'],
		['name' => 'Barbados', 'code' => 'BB'],
		['name' => 'Belarus', 'code' => 'BY'],
		['name' => 'Belgium', 'code' => 'BE'],
		['name' => 'Belize', 'code' => 'BZ'],
		['name' => 'Benin', 'code' => 'BJ'],
		['name' => 'Bermuda', 'code' => 'BM'],
		['name' => 'Bhutan', 'code' => 'BT'],
		['name' => 'Bolivia', 'code' => 'BO'],
		['name' => 'Bosnia and Herzegovina', 'code' => 'BA'],
		['name' => 'Botswana', 'code' => 'BW'],
		['name' => 'Bouvet Island', 'code' => 'BV'],
		['name' => 'Brazil', 'code' => 'BR'],
		['name' => 'British Indian Ocean Territory', 'code' => 'IO'],
		['name' => 'Brunei Darussalam', 'code' => 'BN'],
		['name' => 'Bulgaria', 'code' => 'BG'],
		['name' => 'Burkina Faso', 'code' => 'BF'],
		['name' => 'Burundi', 'code' => 'BI'],
		['name' => 'Cambodia', 'code' => 'KH'],
		['name' => 'Cameroon', 'code' => 'CM'],
		['name' => 'Canada', 'code' => 'CA'],
		['name' => 'Cape Verde', 'code' => 'CV'],
		['name' => 'Cayman Islands', 'code' => 'KY'],
		['name' => 'Central African Republic', 'code' => 'CF'],
		['name' => 'Chad', 'code' => 'TD'],
		['name' => 'Chile', 'code' => 'CL'],
		['name' => 'China', 'code' => 'CN'],
		['name' => 'Christmas Island', 'code' => 'CX'],
		['name' => 'Cocos (Keeling) Islands', 'code' => 'CC'],
		['name' => 'Colombia', 'code' => 'CO'],
		['name' => 'Comoros', 'code' => 'KM'],
		['name' => 'Congo', 'code' => 'CG'],
		['name' => 'Congo, The Democratic Republic of the', 'code' => 'CD'],
		['name' => 'Cook Islands', 'code' => 'CK'],
		['name' => 'Costa Rica', 'code' => 'CR'],
		['name' => 'Cote D\'Ivoire', 'code' => 'CI'],
		['name' => 'Croatia', 'code' => 'HR'],
		['name' => 'Cuba', 'code' => 'CU'],
		['name' => 'Cyprus', 'code' => 'CY'],
		['name' => 'Czech Republic', 'code' => 'CZ'],
		['name' => 'Denmark', 'code' => 'DK'],
		['name' => 'Djibouti', 'code' => 'DJ'],
		['name' => 'Dominica', 'code' => 'DM'],
		['name' => 'Dominican Republic', 'code' => 'DO'],
		['name' => 'Ecuador', 'code' => 'EC'],
		['name' => 'Egypt', 'code' => 'EG'],
		['name' => 'El Salvador', 'code' => 'SV'],
		['name' => 'Equatorial Guinea', 'code' => 'GQ'],
		['name' => 'Eritrea', 'code' => 'ER'],
		['name' => 'Estonia', 'code' => 'EE'],
		['name' => 'Ethiopia', 'code' => 'ET'],
		['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK'],
		['name' => 'Faroe Islands', 'code' => 'FO'],
		['name' => 'Fiji', 'code' => 'FJ'],
		['name' => 'Finland', 'code' => 'FI'],
		['name' => 'France', 'code' => 'FR'],
		['name' => 'French Guiana', 'code' => 'GF'],
		['name' => 'French Polynesia', 'code' => 'PF'],
		['name' => 'French Southern Territories', 'code' => 'TF'],
		['name' => 'Gabon', 'code' => 'GA'],
		['name' => 'Gambia', 'code' => 'GM'],
		['name' => 'Georgia', 'code' => 'GE'],
		['name' => 'Germany', 'code' => 'DE'],
		['name' => 'Ghana', 'code' => 'GH'],
		['name' => 'Gibraltar', 'code' => 'GI'],
		['name' => 'Greece', 'code' => 'GR'],
		['name' => 'Greenland', 'code' => 'GL'],
		['name' => 'Grenada', 'code' => 'GD'],
		['name' => 'Guadeloupe', 'code' => 'GP'],
		['name' => 'Guam', 'code' => 'GU'],
		['name' => 'Guatemala', 'code' => 'GT'],
		['name' => 'Guernsey', 'code' => 'GG'],
		['name' => 'Guinea', 'code' => 'GN'],
		['name' => 'Guinea-Bissau', 'code' => 'GW'],
		['name' => 'Guyana', 'code' => 'GY'],
		['name' => 'Haiti', 'code' => 'HT'],
		['name' => 'Heard Island and Mcdonald Islands', 'code' => 'HM'],
		['name' => 'Holy See (Vatican City State)', 'code' => 'VA'],
		['name' => 'Honduras', 'code' => 'HN'],
		['name' => 'Hong Kong', 'code' => 'HK'],
		['name' => 'Hungary', 'code' => 'HU'],
		['name' => 'Iceland', 'code' => 'IS'],
		['name' => 'India', 'code' => 'IN'],
		['name' => 'Indonesia', 'code' => 'ID'],
		['name' => 'Iran, Islamic Republic Of', 'code' => 'IR'],
		['name' => 'Iraq', 'code' => 'IQ'],
		['name' => 'Ireland', 'code' => 'IE'],
		['name' => 'Isle of Man', 'code' => 'IM'],
		['name' => 'Israel', 'code' => 'IL'],
		['name' => 'Italy', 'code' => 'IT'],
		['name' => 'Jamaica', 'code' => 'JM'],
		['name' => 'Japan', 'code' => 'JP'],
		['name' => 'Jersey', 'code' => 'JE'],
		['name' => 'Jordan', 'code' => 'JO'],
		['name' => 'Kazakhstan', 'code' => 'KZ'],
		['name' => 'Kenya', 'code' => 'KE'],
		['name' => 'Kiribati', 'code' => 'KI'],
		['name' => 'Korea, Democratic People\'S Republic of', 'code' => 'KP'],
		['name' => 'Korea, Republic of', 'code' => 'KR'],
		['name' => 'Kuwait', 'code' => 'KW'],
		['name' => 'Kyrgyzstan', 'code' => 'KG'],
		['name' => 'Lao People\'S Democratic Republic', 'code' => 'LA'],
		['name' => 'Latvia', 'code' => 'LV'],
		['name' => 'Lebanon', 'code' => 'LB'],
		['name' => 'Lesotho', 'code' => 'LS'],
		['name' => 'Liberia', 'code' => 'LR'],
		['name' => 'Libyan Arab Jamahiriya', 'code' => 'LY'],
		['name' => 'Liechtenstein', 'code' => 'LI'],
		['name' => 'Lithuania', 'code' => 'LT'],
		['name' => 'Luxembourg', 'code' => 'LU'],
		['name' => 'Macao', 'code' => 'MO'],
		['name' => 'Macedonia, The Former Yugoslav Republic of', 'code' => 'MK'],
		['name' => 'Madagascar', 'code' => 'MG'],
		['name' => 'Malawi', 'code' => 'MW'],
		['name' => 'Malaysia', 'code' => 'MY'],
		['name' => 'Maldives', 'code' => 'MV'],
		['name' => 'Mali', 'code' => 'ML'],
		['name' => 'Malta', 'code' => 'MT'],
		['name' => 'Marshall Islands', 'code' => 'MH'],
		['name' => 'Martinique', 'code' => 'MQ'],
		['name' => 'Mauritania', 'code' => 'MR'],
		['name' => 'Mauritius', 'code' => 'MU'],
		['name' => 'Mayotte', 'code' => 'YT'],
		['name' => 'Mexico', 'code' => 'MX'],
		['name' => 'Micronesia, Federated States of', 'code' => 'FM'],
		['name' => 'Moldova, Republic of', 'code' => 'MD'],
		['name' => 'Monaco', 'code' => 'MC'],
		['name' => 'Mongolia', 'code' => 'MN'],
		['name' => 'Montserrat', 'code' => 'MS'],
		['name' => 'Morocco', 'code' => 'MA'],
		['name' => 'Mozambique', 'code' => 'MZ'],
		['name' => 'Myanmar', 'code' => 'MM'],
		['name' => 'Namibia', 'code' => 'NA'],
		['name' => 'Nauru', 'code' => 'NR'],
		['name' => 'Nepal', 'code' => 'NP'],
		['name' => 'Netherlands', 'code' => 'NL'],
		['name' => 'Netherlands Antilles', 'code' => 'AN'],
		['name' => 'New Caledonia', 'code' => 'NC'],
		['name' => 'New Zealand', 'code' => 'NZ'],
		['name' => 'Nicaragua', 'code' => 'NI'],
		['name' => 'Niger', 'code' => 'NE'],
		['name' => 'Nigeria', 'code' => 'NG'],
		['name' => 'Niue', 'code' => 'NU'],
		['name' => 'Norfolk Island', 'code' => 'NF'],
		['name' => 'Northern Mariana Islands', 'code' => 'MP'],
		['name' => 'Norway', 'code' => 'NO'],
		['name' => 'Oman', 'code' => 'OM'],
		['name' => 'Pakistan', 'code' => 'PK'],
		['name' => 'Palau', 'code' => 'PW'],
		['name' => 'Palestinian Territory, Occupied', 'code' => 'PS'],
		['name' => 'Panama', 'code' => 'PA'],
		['name' => 'Papua New Guinea', 'code' => 'PG'],
		['name' => 'Paraguay', 'code' => 'PY'],
		['name' => 'Peru', 'code' => 'PE'],
		['name' => 'Philippines', 'code' => 'PH'],
		['name' => 'Pitcairn', 'code' => 'PN'],
		['name' => 'Poland', 'code' => 'PL'],
		['name' => 'Portugal', 'code' => 'PT'],
		['name' => 'Puerto Rico', 'code' => 'PR'],
		['name' => 'Qatar', 'code' => 'QA'],
		['name' => 'Reunion', 'code' => 'RE'],
		['name' => 'Romania', 'code' => 'RO'],
		['name' => 'Russian Federation', 'code' => 'RU'],
		['name' => 'RWANDA', 'code' => 'RW'],
		['name' => 'Saint Helena', 'code' => 'SH'],
		['name' => 'Saint Kitts and Nevis', 'code' => 'KN'],
		['name' => 'Saint Lucia', 'code' => 'LC'],
		['name' => 'Saint Pierre and Miquelon', 'code' => 'PM'],
		['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC'],
		['name' => 'Samoa', 'code' => 'WS'],
		['name' => 'San Marino', 'code' => 'SM'],
		['name' => 'Sao Tome and Principe', 'code' => 'ST'],
		['name' => 'Saudi Arabia', 'code' => 'SA'],
		['name' => 'Senegal', 'code' => 'SN'],
		['name' => 'Serbia and Montenegro', 'code' => 'CS'],
		['name' => 'Seychelles', 'code' => 'SC'],
		['name' => 'Sierra Leone', 'code' => 'SL'],
		['name' => 'Singapore', 'code' => 'SG'],
		['name' => 'Slovakia', 'code' => 'SK'],
		['name' => 'Slovenia', 'code' => 'SI'],
		['name' => 'Solomon Islands', 'code' => 'SB'],
		['name' => 'Somalia', 'code' => 'SO'],
		['name' => 'South Africa', 'code' => 'ZA'],
		['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'],
		['name' => 'Spain', 'code' => 'ES'],
		['name' => 'Sri Lanka', 'code' => 'LK'],
		['name' => 'Sudan', 'code' => 'SD'],
		['name' => 'Suriname', 'code' => 'SR'],
		['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ'],
		['name' => 'Swaziland', 'code' => 'SZ'],
		['name' => 'Sweden', 'code' => 'SE'],
		['name' => 'Switzerland', 'code' => 'CH'],
		['name' => 'Syrian Arab Republic', 'code' => 'SY'],
		['name' => 'Taiwan, Province of China', 'code' => 'TW'],
		['name' => 'Tajikistan', 'code' => 'TJ'],
		['name' => 'Tanzania, United Republic of', 'code' => 'TZ'],
		['name' => 'Thailand', 'code' => 'TH'],
		['name' => 'Timor-Leste', 'code' => 'TL'],
		['name' => 'Togo', 'code' => 'TG'],
		['name' => 'Tokelau', 'code' => 'TK'],
		['name' => 'Tonga', 'code' => 'TO'],
		['name' => 'Trinidad and Tobago', 'code' => 'TT'],
		['name' => 'Tunisia', 'code' => 'TN'],
		['name' => 'Turkey', 'code' => 'TR'],
		['name' => 'Turkmenistan', 'code' => 'TM'],
		['name' => 'Turks and Caicos Islands', 'code' => 'TC'],
		['name' => 'Tuvalu', 'code' => 'TV'],
		['name' => 'Uganda', 'code' => 'UG'],
		['name' => 'Ukraine', 'code' => 'UA'],
		['name' => 'United Arab Emirates', 'code' => 'AE'],
		['name' => 'United Kingdom', 'code' => 'GB'],
		['name' => 'United States', 'code' => 'US'],
		['name' => 'United States Minor Outlying Islands', 'code' => 'UM'],
		['name' => 'Uruguay', 'code' => 'UY'],
		['name' => 'Uzbekistan', 'code' => 'UZ'],
		['name' => 'Vanuatu', 'code' => 'VU'],
		['name' => 'Venezuela', 'code' => 'VE'],
		['name' => 'Viet Nam', 'code' => 'VN'],
		['name' => 'Virgin Islands, British', 'code' => 'VG'],
		['name' => 'Virgin Islands, U.S.', 'code' => 'VI'],
		['name' => 'Wallis and Futuna', 'code' => 'WF'],
		['name' => 'Western Sahara', 'code' => 'EH'],
		['name' => 'Yemen', 'code' => 'YE'],
		['name' => 'Zambia', 'code' => 'ZM'],
		['name' => 'Zimbabwe', 'code' => 'ZW']
	];

	const LANG_CODES = [
		['name' => 'Afghanistan', 'lang_code' => 'ps'],
		['name' => 'Albania', 'lang_code' => 'sq'],
		['name' => 'Algeria', 'lang_code' => 'ar'],
		['name' => 'Andorra', 'lang_code' => 'ca'],
		['name' => 'Angola', 'lang_code' => 'pt'],
		['name' => 'Antigua and Barbuda', 'lang_code' => 'en'],
		['name' => 'Argentina', 'lang_code' => 'es'],
		['name' => 'Armenia', 'lang_code' => 'hy'],
		['name' => 'Australia', 'lang_code' => 'en'],
		['name' => 'Austria', 'lang_code' => 'de'],
		['name' => 'Azerbaijan', 'lang_code' => 'az'],
		['name' => 'Bahamas', 'lang_code' => 'en'],
		['name' => 'Bahrain', 'lang_code' => 'ar'],
		['name' => 'Bangladesh', 'lang_code' => 'bn'],
		['name' => 'Barbados', 'lang_code' => 'en'],
		['name' => 'Belarus', 'lang_code' => 'be'],
		['name' => 'Belgium', 'lang_code' => 'nl'],
		['name' => 'Belize', 'lang_code' => 'en'],
		['name' => 'Benin', 'lang_code' => 'fr'],
		['name' => 'Bhutan', 'lang_code' => 'dz'],
		['name' => 'Bolivia', 'lang_code' => 'es'],
		['name' => 'Bosnia and Herzegovina', 'lang_code' => 'bs'],
		['name' => 'Botswana', 'lang_code' => 'en'],
		['name' => 'Brazil', 'lang_code' => 'pt'],
		['name' => 'Brunei', 'lang_code' => 'ms'],
		['name' => 'Bulgaria', 'lang_code' => 'bg'],
		['name' => 'Burkina Faso', 'lang_code' => 'fr'],
		['name' => 'Burundi', 'lang_code' => 'fr'],
		['name' => 'Cabo Verde', 'lang_code' => 'pt'],
		['name' => 'Cambodia', 'lang_code' => 'km'],
		['name' => 'Cameroon', 'lang_code' => 'fr'],
		['name' => 'Canada', 'lang_code' => 'en'],
		['name' => 'Central African Republic', 'lang_code' => 'fr'],
		['name' => 'Chad', 'lang_code' => 'fr'],
		['name' => 'Chile', 'lang_code' => 'es'],
		['name' => 'China', 'lang_code' => 'zh'],
		['name' => 'Colombia', 'lang_code' => 'es'],
		['name' => 'Comoros', 'lang_code' => 'ar'],
		['name' => 'Congo (Congo-Brazzaville)', 'lang_code' => 'fr'],
		['name' => 'Costa Rica', 'lang_code' => 'es'],
		['name' => 'Croatia', 'lang_code' => 'hr'],
		['name' => 'Cuba', 'lang_code' => 'es'],
		['name' => 'Cyprus', 'lang_code' => 'el'],
		['name' => 'Czech Republic', 'lang_code' => 'cs'],
		['name' => 'Democratic Republic of the Congo', 'lang_code' => 'fr'],
		['name' => 'Denmark', 'lang_code' => 'da'],
		['name' => 'Djibouti', 'lang_code' => 'fr'],
		['name' => 'Dominica', 'lang_code' => 'en'],
		['name' => 'Dominican Republic', 'lang_code' => 'es'],
		['name' => 'Ecuador', 'lang_code' => 'es'],
		['name' => 'Egypt', 'lang_code' => 'ar'],
		['name' => 'El Salvador', 'lang_code' => 'es'],
		['name' => 'Equatorial Guinea', 'lang_code' => 'es'],
		['name' => 'Eritrea', 'lang_code' => 'ti'],
		['name' => 'Estonia', 'lang_code' => 'et'],
		['name' => 'Eswatini (Swaziland)', 'lang_code' => 'en'],
		['name' => 'Ethiopia', 'lang_code' => 'am'],
		['name' => 'Fiji', 'lang_code' => 'en'],
		['name' => 'Finland', 'lang_code' => 'fi'],
		['name' => 'France', 'lang_code' => 'fr'],
		['name' => 'Gabon', 'lang_code' => 'fr'],
		['name' => 'Gambia', 'lang_code' => 'en'],
		['name' => 'Georgia', 'lang_code' => 'ka'],
		['name' => 'Germany', 'lang_code' => 'de'],
		['name' => 'Ghana', 'lang_code' => 'en'],
		['name' => 'Greece', 'lang_code' => 'el'],
		['name' => 'Grenada', 'lang_code' => 'en'],
		['name' => 'Guatemala', 'lang_code' => 'es'],
		['name' => 'Guinea', 'lang_code' => 'fr'],
		['name' => 'Guinea-Bissau', 'lang_code' => 'pt'],
		['name' => 'Guyana', 'lang_code' => 'en'],
		['name' => 'Haiti', 'lang_code' => 'ht'],
		['name' => 'Honduras', 'lang_code' => 'es'],
		['name' => 'Hungary', 'lang_code' => 'hu'],
		['name' => 'Iceland', 'lang_code' => 'is'],
		['name' => 'India', 'lang_code' => 'hi'],
		['name' => 'Indonesia', 'lang_code' => 'id'],
		['name' => 'Iran', 'lang_code' => 'fa'],
		['name' => 'Iraq', 'lang_code' => 'ar'],
		['name' => 'Ireland', 'lang_code' => 'en'],
		['name' => 'Israel', 'lang_code' => 'he'],
		['name' => 'Italy', 'lang_code' => 'it'],
		['name' => 'Jamaica', 'lang_code' => 'en'],
		['name' => 'Japan', 'lang_code' => 'ja'],
		['name' => 'Jordan', 'lang_code' => 'ar'],
		['name' => 'Kazakhstan', 'lang_code' => 'kk'],
		['name' => 'Kenya', 'lang_code' => 'en'],
		['name' => 'Kiribati', 'lang_code' => 'en'],
		['name' => 'Korea, North', 'lang_code' => 'ko'],
		['name' => 'Korea, South', 'lang_code' => 'ko'],
		['name' => 'Kosovo', 'lang_code' => 'sq'],
		['name' => 'Kuwait', 'lang_code' => 'ar'],
		['name' => 'Kyrgyzstan', 'lang_code' => 'ky'],
		['name' => 'Laos', 'lang_code' => 'lo'],
		['name' => 'Latvia', 'lang_code' => 'lv'],
		['name' => 'Lebanon', 'lang_code' => 'ar'],
		['name' => 'Lesotho', 'lang_code' => 'st'],
		['name' => 'Liberia', 'lang_code' => 'en'],
		['name' => 'Libya', 'lang_code' => 'ar'],
		['name' => 'Liechtenstein', 'lang_code' => 'de'],
		['name' => 'Lithuania', 'lang_code' => 'lt'],
		['name' => 'Luxembourg', 'lang_code' => 'lb'],
		['name' => 'Madagascar', 'lang_code' => 'mg'],
		['name' => 'Malawi', 'lang_code' => 'ny'],
		['name' => 'Malaysia', 'lang_code' => 'ms'],
		['name' => 'Maldives', 'lang_code' => 'dv'],
		['name' => 'Mali', 'lang_code' => 'fr'],
		['name' => 'Malta', 'lang_code' => 'mt'],
		['name' => 'Marshall Islands', 'lang_code' => 'en'],
		['name' => 'Mauritania', 'lang_code' => 'ar'],
		['name' => 'Mauritius', 'lang_code' => 'en'],
		['name' => 'Mexico', 'lang_code' => 'es'],
		['name' => 'Micronesia', 'lang_code' => 'en'],
		['name' => 'Moldova', 'lang_code' => 'ro'],
		['name' => 'Monaco', 'lang_code' => 'fr'],
		['name' => 'Mongolia', 'lang_code' => 'mn'],
		['name' => 'Montenegro', 'lang_code' => 'sr'],
		['name' => 'Morocco', 'lang_code' => 'ar'],
		['name' => 'Mozambique', 'lang_code' => 'pt'],
		['name' => 'Myanmar (formerly Burma)', 'lang_code' => 'my'],
		['name' => 'Namibia', 'lang_code' => 'en'],
		['name' => 'Nauru', 'lang_code' => 'en'],
		['name' => 'Nepal', 'lang_code' => 'ne'],
		['name' => 'Netherlands', 'lang_code' => 'nl'],
		['name' => 'New Zealand', 'lang_code' => 'en'],
		['name' => 'Nicaragua', 'lang_code' => 'es'],
		['name' => 'Niger', 'lang_code' => 'fr'],
		['name' => 'Nigeria', 'lang_code' => 'en'],
		['name' => 'North Macedonia', 'lang_code' => 'mk'],
		['name' => 'Norway', 'lang_code' => 'no'],
		['name' => 'Oman', 'lang_code' => 'ar'],
		['name' => 'Pakistan', 'lang_code' => 'ur'],
		['name' => 'Palau', 'lang_code' => 'en'],
		['name' => 'Palestine State', 'lang_code' => 'ar'],
		['name' => 'Panama', 'lang_code' => 'es'],
		['name' => 'Papua New Guinea', 'lang_code' => 'en'],
		['name' => 'Paraguay', 'lang_code' => 'es'],
		['name' => 'Peru', 'lang_code' => 'es'],
		['name' => 'Philippines', 'lang_code' => 'en'],
		['name' => 'Poland', 'lang_code' => 'pl'],
		['name' => 'Portugal', 'lang_code' => 'pt'],
		['name' => 'Qatar', 'lang_code' => 'ar'],
		['name' => 'Romania', 'lang_code' => 'ro'],
		['name' => 'Russia', 'lang_code' => 'ru'],
		['name' => 'Rwanda', 'lang_code' => 'rw'],
		['name' => 'Saint Kitts and Nevis', 'lang_code' => 'en'],
		['name' => 'Saint Lucia', 'lang_code' => 'en'],
		['name' => 'Saint Vincent and the Grenadines', 'lang_code' => 'en'],
		['name' => 'Samoa', 'lang_code' => 'en'],
		['name' => 'San Marino', 'lang_code' => 'it'],
		['name' => 'Sao Tome and Principe', 'lang_code' => 'pt'],
		['name' => 'Saudi Arabia', 'lang_code' => 'ar'],
		['name' => 'Senegal', 'lang_code' => 'fr'],
		['name' => 'Serbia', 'lang_code' => 'sr'],
		['name' => 'Seychelles', 'lang_code' => 'fr'],
		['name' => 'Sierra Leone', 'lang_code' => 'en'],
		['name' => 'Singapore', 'lang_code' => 'en'],
		['name' => 'Slovakia', 'lang_code' => 'sk'],
		['name' => 'Slovenia', 'lang_code' => 'sl'],
		['name' => 'Solomon Islands', 'lang_code' => 'en'],
		['name' => 'Somalia', 'lang_code' => 'so'],
		['name' => 'South Africa', 'lang_code' => 'en'],
		['name' => 'South Sudan', 'lang_code' => 'en'],
		['name' => 'Spain', 'lang_code' => 'es'],
		['name' => 'Sri Lanka', 'lang_code' => 'si'],
		['name' => 'Sudan', 'lang_code' => 'ar'],
		['name' => 'Suriname', 'lang_code' => 'nl'],
		['name' => 'Sweden', 'lang_code' => 'sv'],
		['name' => 'Switzerland', 'lang_code' => 'de'],
		['name' => 'Syria', 'lang_code' => 'ar'],
		['name' => 'Tajikistan', 'lang_code' => 'tg'],
		['name' => 'Tanzania', 'lang_code' => 'sw'],
		['name' => 'Thailand', 'lang_code' => 'th'],
		['name' => 'Togo', 'lang_code' => 'fr'],
		['name' => 'Tonga', 'lang_code' => 'en'],
		['name' => 'Trinidad and Tobago', 'lang_code' => 'en'],
		['name' => 'Tunisia', 'lang_code' => 'ar'],
		['name' => 'Turkey', 'lang_code' => 'tr'],
		['name' => 'Turkmenistan', 'lang_code' => 'tk'],
		['name' => 'Tuvalu', 'lang_code' => 'en'],
		['name' => 'Uganda', 'lang_code' => 'en'],
		['name' => 'Ukraine', 'lang_code' => 'uk'],
		['name' => 'United Arab Emirates', 'lang_code' => 'ar'],
		['name' => 'United Kingdom', 'lang_code' => 'en'],
		['name' => 'United States of America', 'lang_code' => 'en'],
		['name' => 'Uruguay', 'lang_code' => 'es'],
		['name' => 'Uzbekistan', 'lang_code' => 'uz'],
		['name' => 'Vanuatu', 'lang_code' => 'en'],
		['name' => 'Vatican City', 'lang_code' => 'la'],
		['name' => 'Venezuela', 'lang_code' => 'es'],
		['name' => 'Vietnam', 'lang_code' => 'vi'],
		['name' => 'Yemen', 'lang_code' => 'ar'],
		['name' => 'Zambia', 'lang_code' => 'en'],
		['name' => 'Zimbabwe', 'lang_code' => 'en'],
	];

	const POPULAR_LANG_CODES = [
		['name' => 'English',     'lang_code' => 'en'],
		['name' => 'Spanish',     'lang_code' => 'es'],
		['name' => 'Arabic',      'lang_code' => 'ar'],
		['name' => 'French',      'lang_code' => 'fr'],
		['name' => 'German',      'lang_code' => 'de'],
		['name' => 'Portuguese',  'lang_code' => 'pt'],
		['name' => 'Russian',     'lang_code' => 'ru'],
		['name' => 'Chinese',     'lang_code' => 'zh'],
		['name' => 'Japanese',    'lang_code' => 'ja'],
		['name' => 'Korean',      'lang_code' => 'ko'],
		['name' => 'Hindi',       'lang_code' => 'hi'],
		['name' => 'Bengali',     'lang_code' => 'bn'],
		['name' => 'Italian',     'lang_code' => 'it'],
		['name' => 'Turkish',     'lang_code' => 'tr'],
		['name' => 'Dutch',       'lang_code' => 'nl'],
		['name' => 'Polish',      'lang_code' => 'pl'],
		['name' => 'Ukrainian',   'lang_code' => 'uk'],
		['name' => 'Vietnamese',  'lang_code' => 'vi'],
		['name' => 'Thai',        'lang_code' => 'th'],
		['name' => 'Swedish',     'lang_code' => 'sv'],
	];

	const  TELEPHONE_CODES = [
		['name' => 'UK (+44)', 'code' => '44'],
		['name' => 'USA (+1)', 'code' => '1'],
		['name' => 'Algeria (+213)', 'code' => '213'],
		['name' => 'Andorra (+376)', 'code' => '376'],
		['name' => 'Angola (+244)', 'code' => '244'],
		['name' => 'Anguilla (+1264)', 'code' => '1264'],
		['name' => 'Antigua & Barbuda (+1268)', 'code' => '1268'],
		['name' => 'Argentina (+54)', 'code' => '54'],
		['name' => 'Armenia (+374)', 'code' => '374'],
		['name' => 'Aruba (+297)', 'code' => '297'],
		['name' => 'Australia (+61)', 'code' => '61'],
		['name' => 'Austria (+43)', 'code' => '43'],
		['name' => 'Azerbaijan (+994)', 'code' => '994'],
		['name' => 'Bahamas (+1242)', 'code' => '1242'],
		['name' => 'Bahrain (+973)', 'code' => '973'],
		['name' => 'Bangladesh (+880)', 'code' => '880'],
		['name' => 'Barbados (+1246)', 'code' => '1246'],
		['name' => 'Belarus (+375)', 'code' => '375'],
		['name' => 'Belgium (+32)', 'code' => '32'],
		['name' => 'Belize (+501)', 'code' => '501'],
		['name' => 'Benin (+229)', 'code' => '229'],
		['name' => 'Bermuda (+1441)', 'code' => '1441'],
		['name' => 'Bhutan (+975)', 'code' => '975'],
		['name' => 'Bolivia (+591)', 'code' => '591'],
		['name' => 'Bosnia Herzegovina (+387)', 'code' => '387'],
		['name' => 'Botswana (+267)', 'code' => '267'],
		['name' => 'Brazil (+55)', 'code' => '55'],
		['name' => 'Brunei (+673)', 'code' => '673'],
		['name' => 'Bulgaria (+359)', 'code' => '359'],
		['name' => 'Burkina Faso (+226)', 'code' => '226'],
		['name' => 'Burundi (+257)', 'code' => '257'],
		['name' => 'Cambodia (+855)', 'code' => '855'],
		['name' => 'Cameroon (+237)', 'code' => '237'],
		['name' => 'Canada (+1)', 'code' => '1'],
		['name' => 'Cape Verde Islands (+238)', 'code' => '238'],
		['name' => 'Cayman Islands (+1345)', 'code' => '1345'],
		['name' => 'Central African Republic (+236)', 'code' => '236'],
		['name' => 'Chile (+56)', 'code' => '56'],
		['name' => 'China (+86)', 'code' => '86'],
		['name' => 'Colombia (+57)', 'code' => '57'],
		['name' => 'Comoros (+269)', 'code' => '269'],
		['name' => 'Congo (+242)', 'code' => '242'],
		['name' => 'Cook Islands (+682)', 'code' => '682'],
		['name' => "COTE D'IVOIRE (+225)", 'code' => '225'],
		['name' => 'Costa Rica (+506)', 'code' => '506'],
		['name' => 'Croatia (+385)', 'code' => '385'],
		['name' => 'Cuba (+53)', 'code' => '53'],
		['name' => 'Cyprus North (+90392)', 'code' => '90392'],
		['name' => 'Cyprus South (+357)', 'code' => '357'],
		['name' => 'Czech Republic (+42)', 'code' => '42'],
		['name' => 'Denmark (+45)', 'code' => '45'],
		['name' => 'Djibouti (+253)', 'code' => '253'],
		['name' => 'Dominica (+1767)', 'code' => '1767'],
		['name' => 'Dominican Republic (+1809)', 'code' => '1809'],
		['name' => 'Ecuador (+593)', 'code' => '593'],
		['name' => 'Egypt (+20)', 'code' => '20'],
		['name' => 'El Salvador (+503)', 'code' => '503'],
		['name' => 'Equatorial Guinea (+240)', 'code' => '240'],
		['name' => 'Eritrea (+291)', 'code' => '291'],
		['name' => 'Estonia (+372)', 'code' => '372'],
		['name' => 'Ethiopia (+251)', 'code' => '251'],
		['name' => 'Falkland Islands (+500)', 'code' => '500'],
		['name' => 'Faroe Islands (+298)', 'code' => '298'],
		['name' => 'Fiji (+679)', 'code' => '679'],
		['name' => 'Finland (+358)', 'code' => '358'],
		['name' => 'France (+33)', 'code' => '33'],
		['name' => 'French Guiana (+594)', 'code' => '594'],
		['name' => 'French Polynesia (+689)', 'code' => '689'],
		['name' => 'Gabon (+241)', 'code' => '241'],
		['name' => 'Gambia (+220)', 'code' => '220'],
		['name' => 'Georgia (+7880)', 'code' => '7880'],
		['name' => 'Germany (+49)', 'code' => '49'],
		['name' => 'Ghana (+233)', 'code' => '233'],
		['name' => 'Gibraltar (+350)', 'code' => '350'],
		['name' => 'Greece (+30)', 'code' => '30'],
		['name' => 'Greenland (+299)', 'code' => '299'],
		['name' => 'Grenada (+1473)', 'code' => '1473'],
		['name' => 'Guadeloupe (+590)', 'code' => '590'],
		['name' => 'Guam (+671)', 'code' => '671'],
		['name' => 'Guatemala (+502)', 'code' => '502'],
		['name' => 'Guinea (+224)', 'code' => '224'],
		['name' => 'Guinea - Bissau (+245)', 'code' => '245'],
		['name' => 'Guyana (+592)', 'code' => '592'],
		['name' => 'Haiti (+509)', 'code' => '509'],
		['name' => 'Honduras (+504)', 'code' => '504'],
		['name' => 'Hong Kong (+852)', 'code' => '852'],
		['name' => 'Hungary (+36)', 'code' => '36'],
		['name' => 'Iceland (+354)', 'code' => '354'],
		['name' => 'India (+91)', 'code' => '91'],
		['name' => 'Indonesia (+62)', 'code' => '62'],
		['name' => 'Iran (+98)', 'code' => '98'],
		['name' => 'Iraq (+964)', 'code' => '964'],
		['name' => 'Ireland (+353)', 'code' => '353'],
		['name' => 'Israel (+972)', 'code' => '972'],
		['name' => 'Italy (+39)', 'code' => '39'],
		['name' => 'Jamaica (+1876)', 'code' => '1876'],
		['name' => 'Japan (+81)', 'code' => '81'],
		['name' => 'Jordan (+962)', 'code' => '962'],
		['name' => 'Kazakhstan (+7)', 'code' => '7'],
		['name' => 'Kenya (+254)', 'code' => '254'],
		['name' => 'Kiribati (+686)', 'code' => '686'],
		['name' => 'Korea North (+850)', 'code' => '850'],
		['name' => 'Korea South (+82)', 'code' => '82'],
		['name' => 'Kuwait (+965)', 'code' => '965'],
		['name' => 'Kyrgyzstan (+996)', 'code' => '996'],
		['name' => 'Laos (+856)', 'code' => '856'],
		['name' => 'Latvia (+371)', 'code' => '371'],
		['name' => 'Lebanon (+961)', 'code' => '961'],
		['name' => 'Lesotho (+266)', 'code' => '266'],
		['name' => 'Liberia (+231)', 'code' => '231'],
		['name' => 'Libya (+218)', 'code' => '218'],
		['name' => 'Liechtenstein (+417)', 'code' => '417'],
		['name' => 'Lithuania (+370)', 'code' => '370'],
		['name' => 'Luxembourg (+352)', 'code' => '352'],
		['name' => 'Macao (+853)', 'code' => '853'],
		['name' => 'Macedonia (+389)', 'code' => '389'],
		['name' => 'Madagascar (+261)', 'code' => '261'],
		['name' => 'Malawi (+265)', 'code' => '265'],
		['name' => 'Malaysia (+60)', 'code' => '60'],
		['name' => 'Maldives (+960)', 'code' => '960'],
		['name' => 'Mali (+223)', 'code' => '223'],
		['name' => 'Malta (+356)', 'code' => '356'],
		['name' => 'Marshall Islands (+692)', 'code' => '692'],
		['name' => 'Martinique (+596)', 'code' => '596'],
		['name' => 'Mauritania (+222)', 'code' => '222'],
		['name' => 'Mayotte (+269)', 'code' => '269'],
		['name' => 'Mexico (+52)', 'code' => '52'],
		['name' => 'Micronesia (+691)', 'code' => '691'],
		['name' => 'Moldova (+373)', 'code' => '373'],
		['name' => 'Monaco (+377)', 'code' => '377'],
		['name' => 'Montserrat (+1664)', 'code' => '1664'],
		['name' => 'Morocco (+212)', 'code' => '212'],
		['name' => 'Mozambique (+258)', 'code' => '258'],
		['name' => 'Myanmar (+95)', 'code' => '95'],
		['name' => 'Namibia (+264)', 'code' => '264'],
		['name' => 'Nauru (+674)', 'code' => '674'],
		['name' => 'Nepal (+977)', 'code' => '977'],
		['name' => 'Netherlands (+31)', 'code' => '31'],
		['name' => 'New Caledonia (+687)', 'code' => '687'],
		['name' => 'New Zealand (+64)', 'code' => '64'],
		['name' => 'Nicaragua (+505)', 'code' => '505'],
		['name' => 'Niger (+227)', 'code' => '227'],
		['name' => 'Nigeria (+234)', 'code' => '234'],
		['name' => 'Niue (+683)', 'code' => '683'],
		['name' => 'Norfolk Islands (+672)', 'code' => '672'],
		['name' => 'Northern Marianas (+670)', 'code' => '670'],
		['name' => 'Norway (+47)', 'code' => '47'],
		['name' => 'Oman (+968)', 'code' => '968'],
		['name' => 'Pakistan (+92)', 'code' => '92'],
		['name' => 'Palau (+680)', 'code' => '680'],
		['name' => 'Panama (+507)', 'code' => '507'],
		['name' => 'Papua New Guinea (+675)', 'code' => '675'],
		['name' => 'Paraguay (+595)', 'code' => '595'],
		['name' => 'Peru (+51)', 'code' => '51'],
		['name' => 'Philippines (+63)', 'code' => '63'],
		['name' => 'Poland (+48)', 'code' => '48'],
		['name' => 'Portugal (+351)', 'code' => '351'],
		['name' => 'Qatar (+974)', 'code' => '974'],
		['name' => 'Reunion (+262)', 'code' => '262'],
		['name' => 'Romania (+40)', 'code' => '40'],
		['name' => 'Russia (+7)', 'code' => '7'],
		['name' => 'Rwanda (+250)', 'code' => '250'],
		['name' => 'San Marino (+378)', 'code' => '378'],
		['name' => 'Sao Tome & Principe (+239)', 'code' => '239'],
		['name' => 'Saudi Arabia (+966)', 'code' => '966'],
		['name' => 'Senegal (+221)', 'code' => '221'],
		['name' => 'Serbia (+381)', 'code' => '381'],
		['name' => 'Seychelles (+248)', 'code' => '248'],
		['name' => 'Sierra Leone (+232)', 'code' => '232'],
		['name' => 'Singapore (+65)', 'code' => '65'],
		['name' => 'Slovak Republic (+421)', 'code' => '421'],
		['name' => 'Slovenia (+386)', 'code' => '386'],
		['name' => 'Solomon Islands (+677)', 'code' => '677'],
		['name' => 'Somalia (+252)', 'code' => '252'],
		['name' => 'South Africa (+27)', 'code' => '27'],
		['name' => 'Spain (+34)', 'code' => '34'],
		['name' => 'Sri Lanka (+94)', 'code' => '94'],
		['name' => 'St. Helena (+290)', 'code' => '290'],
		['name' => 'St. Kitts (+1869)', 'code' => '1869'],
		['name' => 'St. Lucia (+1758)', 'code' => '1758'],
		['name' => 'Sudan (+249)', 'code' => '249'],
		['name' => 'Suriname (+597)', 'code' => '597'],
		['name' => 'Swaziland (+268)', 'code' => '268'],
		['name' => 'Sweden (+46)', 'code' => '46'],
		['name' => 'Switzerland (+41)', 'code' => '41'],
		['name' => 'Syria (+963)', 'code' => '963'],
		['name' => 'Taiwan (+886)', 'code' => '886'],
		['name' => 'Tajikstan (+7)', 'code' => '7'],
		['name' => 'Thailand (+66)', 'code' => '66'],
		['name' => 'Togo (+228)', 'code' => '228'],
		['name' => 'Tonga (+676)', 'code' => '676'],
		['name' => 'Trinidad & Tobago (+1868)', 'code' => '1868'],
		['name' => 'Tunisia (+216)', 'code' => '216'],
		['name' => 'Turkey (+90)', 'code' => '90'],
		['name' => 'Turkmenistan (+7)', 'code' => '7'],
		['name' => 'Turkmenistan (+993)', 'code' => '993'],
		['name' => 'Turks & Caicos Islands (+1649)', 'code' => '1649'],
		['name' => 'Tuvalu (+688)', 'code' => '688'],
		['name' => 'Uganda (+256)', 'code' => '256'],
		['name' => 'Ukraine (+380)', 'code' => '380'],
		['name' => 'United Arab Emirates (+971)', 'code' => '971'],
		['name' => 'Uruguay (+598)', 'code' => '598'],
		['name' => 'Uzbekistan (+7)', 'code' => '7'],
		['name' => 'Vanuatu (+678)', 'code' => '678'],
		['name' => 'Vatican City (+379)', 'code' => '379'],
		['name' => 'Venezuela (+58)', 'code' => '58'],
		['name' => 'Vietnam (+84)', 'code' => '84'],
		['name' => 'Virgin Islands - British (+1284)', 'code' => '1284'],
		['name' => 'Virgin Islands - US (+1340)', 'code' => '1340'],
		['name' => 'Wallis & Futuna (+681)', 'code' => '681'],
		['name' => 'Yemen (North)(+969)', 'code' => '969'],
		['name' => 'Yemen (South)(+967)', 'code' => '967'],
		['name' => 'Zambia (+260)', 'code' => '260'],
		['name' => 'Zimbabwe (+263)', 'code' => '263'],
	];

	const SETTINGS_JSON_KEYS = [
		SettingKey::S3_CONFIGURATION->value,
		SettingKey::FTP_CONFIGURATION->value,
		SettingKey::ADDRESS->value,
		SettingKey::SUPPORT_LINKS->value,
		SettingKey::QUICK_ACTIONS->value
	];

	const SUPPORTED_FILE_TYPE = ['3dmf',    '3dm',    'avi',    'ai',    'bin',    'bin',    'bmp',    'cab',    'c',    'c++',    'class',    'css',    'csv',    'cdr',    'doc',    'dot',    'docx',    'dwg',    'eps',    'exe',    'gif',    'gz',    'gtar',    'flv',    'fh4',    'fh5',    'fhc',    'help',    'hlp',    'html',    'htm',    'ico',    'imap',    'inf',    'jpe',    'jpeg',    'jpg',    'js',    'java',    'latex',    'log',    'm3u',    'midi',    'mid',    'mov',    'mp3',    'mpeg',    'mpg',    'mp2',    'ogg',    'phtml',    'php',    'pdf',    'pgp',    'png',    'pps',    'ppt',    'ppz',    'pot',    'ps',    'qt',    'qd3d',    'qd3',    'qxd',    'rar',    'ra',    'ram',    'rm',    'rtf',    'spr',    'sprite',    'stream',    'swf',    'svg',    'sgml',    'sgm',    'tar',    'tiff',    'tif',    'tgz',    'tex',    'txt',    'vob',    'wav',    'wrl',    'wrl',    'xla',    'xls',    'xls',    'xlc',    'xml',    'xlsx',    'zip', 'mp4', 'webp'];

	const SUPPORTED_IMAGE_MIMES = ['jpeg', 'png', 'jpg', 'webp', 'ico'];

	const SUPPORTED_IMPORTABLE_MIMES = [
		'csv',
		'txt',
		'xls',
		'xlsx',
		'xlsm',
		'xlt',
		'xltx',
		'xltm'
	];

	const MAX_IMPORT_FILE_SIZE_MB    = 30;
	const MAX_IMPORT_FILE_SIZE_BYTES = 30 * 1024 * 1024;

	const CURRENCY_ALIGNMENT = [
		'[symbol][amount]',
		'[amount][symbol]',
		'[symbol] [amount]',
		'[amount] [symbol]'
	];

	const DATE_FORMAT = [
		'd M, Y',
		'm.d.y',
		'Y-m-d',
		'd-m-Y',
		'd/m/Y',
		'Y/m/d'
	];

	const TIME_FORMAT = [
		'h:i A',
		'h:i:s A',
		'H:i',
		'H:i:s'
	];

	const DEFAULT_TEMPLATE_CODE = [
		'name'          => 'Name',
		'message'       => 'Message',
		'company_email' => 'Email',
		'company_phone' => 'Phone Number',
		'company_name'  => 'Company name',
		'company_logo'  => 'Company logo'
	];

	const DEFAULT_MAIL_TEMPLATE = '{{message}}';

	const DEFAULT_SMS_TEMPLATE  = '{{message}}';
	const DEFAULT_PUSH_TEMPLATE = '{{message}}';

	/**
	 * Visitor theme cookie. Single source of truth for the active theme.
	 * Must stay unencrypted (see bootstrap/app.php) so JS can read/write it.
	 */
	const THEME_COOKIE_NAME    = 'qtech_theme';
	const THEME_COOKIE_MAX_AGE = 60 * 60 * 24 * 365;

	public static function countryNames(): array
	{
		return array_column(self::COUNTRIES, 'name');
	}
}
