import { OtpVerificationForm } from '@/Components/Forms/Backend/Auth/OtpVerificationForm'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/Components/UI/Card'
import { useTranslations } from '@/Hooks/useTranslations'
import GuestLayout from '@/Layouts/GuestLayout'
import { Head } from '@inertiajs/react'

interface TwoFactorVerificationProps {
  title: string
}

export default function TwoFactorVerification({
  title,
}: TwoFactorVerificationProps) {

  const {t} = useTranslations();
  return (
    <GuestLayout title={title}>
      <Head title={title} />

      <Card className="gap-4">
        <CardHeader>
          <CardTitle className="text-lg tracking-tight">
             {t('2FA Verification')}
          </CardTitle>
          <CardDescription>
              {t('Please enter the 6-digit authentication code generated by your Google Authenticator app.')}
          </CardDescription>
        </CardHeader>

        <CardContent>
          <OtpVerificationForm isGoogle2fa />
        </CardContent>
      </Card>
    </GuestLayout>
  )
}
